### ISSUE TITLE
能否发一份baidu_qa_2019的数据集

### ISSUE THREAD

**Issue by CheRryLeit** [atom-zh/SA_Classification#2]
作者你好，能否发给我一份baidu_qa_2019的数据集，我现在只有100条，在其他仓库里下载也只有100条，没有全部的，邮箱1099438405@qq.com，多谢

**Comment by atom-zh** [comment]
> 1099438405@qq.com

已发。

**Comment by atom-zh** [comment]
> 作者你好，能否发给我一份baidu_qa_2019的数据集，我现在只有100条，在其他仓库里下载也只有100条，没有全部的，邮箱[1099438405@qq.com](mailto:1099438405@qq.com)，多谢

已发。
